# Generated by Django 4.2.15 on 2024-08-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
