# Generated by Django 4.2.15 on 2024-08-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLearning_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLearning_app.student')),
            ],
        ),
    ]
