# Generated by Django 4.2.15 on 2024-09-06 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_app', '0002_alter_feedback_rating_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blocked_students',
            field=models.ManyToManyField(blank=True, related_name='blocked_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlockNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLearning_app.course')),
                ('student', models.ForeignKey(limit_choices_to=models.Q(('user_type', 'student')), on_delete=django.db.models.deletion.CASCADE, to='eLearning_app.elearnuser')),
            ],
        ),
    ]
