# Generated by Django 4.2.15 on 2024-09-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_app', '0003_course_blocked_students_blocknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocknotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
