# Generated by Django 4.2.15 on 2024-08-21 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_app', '0003_alter_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eLearning_app.elearnuser'),
            preserve_default=False,
        ),
    ]
