# Generated by Django 4.2.15 on 2024-09-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_app', '0006_coursediscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eLearning_app.course'),
        ),
    ]
